name: build-emulated-test

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build-emulated:
    name: Build on emulated ${{matrix.architecture}} Linux platform
    strategy:
      matrix:
        architecture: [ppc64]
        include:
          - architecture: ppc64
            container: quay.io/pypa/manylinux_2_28_ppc64le
          # - architecutre: s390x
          #   container: quay.io/pypa/manylinux_2_28_s390x
          # - architecutre: i686
          #   container: quay.io/pypa/manylinux_2_28_i686
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: [${{matrix.architecture}}]

      - name: Start docker container
        run: docker run -di ${{matrix.container}}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
